name: Build Electron App

on:
  push:
    branches: [ "master" ]
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.20.0

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run build

      - name: Set artifact path
        id: set-artifact-path
        shell: bash
        run: |
            if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                echo "artifact_path=dist-electron/*.dmg" >> $GITHUB_OUTPUT
            elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                echo "artifact_path=dist-electron/*Setup*.exe" >> $GITHUB_OUTPUT
            else
                echo "artifact_path=dist-electron/*.AppImage" >> $GITHUB_OUTPUT
            fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KimiNoBan-${{ matrix.os }}
          path: ${{ steps.set-artifact-path.outputs.artifact_path }}
